#!/bin/bash
#SBATCH --job-name=sft-overspecific
#SBATCH --output=sft-overspecific-%j.out
#SBATCH --error=sft-overspecific-%j.err
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=4

# SFT training on overspecific reasoning data generated by create_sft_data.py
#
# Prerequisite: Run SFT data generation first:
#   sbatch scripts/run_sft_generation.sh
#
# This trains the model on completions that heavily reference context-specific
# details (role, organization, tool, domain), testing whether overspecific
# reasoning reduces generalization to test contexts.
#
# NOTE: For --full-finetune, increase --mem to 64G or higher
#
# After training, evaluate with:
#   uv run python eval.py outputs/sft-overspecific/merged --task canary --split test

set -e

# Get the script's actual directory, resolving symlinks
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SLURM_SUBMIT_DIR:-$SCRIPT_DIR/../..}"

# Create logs directory and move SLURM output files there
mkdir -p logs
if [ -n "$SLURM_JOB_ID" ]; then
    # Move SLURM output files to logs/ (they start in submit dir)
    for f in sft-overspecific-${SLURM_JOB_ID}.out sft-overspecific-${SLURM_JOB_ID}.err; do
        [ -f "$f" ] && mv "$f" logs/ 2>/dev/null || true
    done
fi

echo "=========================================="
echo "SFT Training on Overspecific Reasoning"
echo "Started: $(date)"
echo "=========================================="

# Default paths
DATASET_PATH="${DATASET_PATH:-data/sft/canary-overspecific}"
OUTPUT_NAME="${OUTPUT_NAME:-sft-overspecific}"

# Check dataset exists
if [ ! -d "$DATASET_PATH" ] && [ ! -f "$DATASET_PATH" ]; then
    echo "ERROR: Dataset not found at $DATASET_PATH"
    echo "Run SFT data generation first: sbatch scripts/run_sft_generation.sh"
    exit 1
fi

echo "Dataset: $DATASET_PATH"
echo "Output: outputs/$OUTPUT_NAME"
echo ""

# Run SFT training
uv run python train_sft.py \
    --dataset-path "$DATASET_PATH" \
    --output "$OUTPUT_NAME" \
    --epochs 1 \
    --save-every 25 \
    "$@"

echo ""
echo "=========================================="
echo "Training complete: $(date)"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Merge checkpoint: uv run python utils/merge_checkpoint.py outputs/$OUTPUT_NAME"
echo "  2. Evaluate: uv run python eval.py outputs/$OUTPUT_NAME/merged --task canary --split test"
